name: procedural_art_generator
description: "A generative art creation application with procedural animations"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  vector_math: ^2.1.4
  uuid: ^4.2.2
  flutter_colorpicker: ^1.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0
  file_picker: ^10.1.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  image: ^4.1.7
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
