name: myapp
description: "A generative art creation tool."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  image: ^4.1.3
  share_plus: ^7.2.1
  flutter_colorpicker: ^1.0.3
  vector_math: ^2.1.4
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
