name: procedural_art_generator
description: "A generative art creation tool with interactive controls and physics-based animations."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  image: ^4.1.3
  share_plus: ^7.2.1
  flutter_colorpicker: ^1.0.3
  vector_math: ^2.1.4
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  uuid: ^4.2.2
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  path: ^1.8.3
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  csv: ^5.1.1
  google_fonts: ^6.1.0
  flutter_displaymode: ^0.6.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
